In [15]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import glob
import os
  
# merging the files
joined_files = os.path.join("database", "JC-201*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)
  
# Finally, the files are joined
df_one = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
df_one

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366256,384,2019-08-31 23:40:45.2450,2019-08-31 23:47:09.8810,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29522,Subscriber,1988,1
366257,633,2019-08-31 23:45:55.6660,2019-08-31 23:56:29.5350,3186,Grove St PATH,40.719586,-74.043117,3185,City Hall,40.717732,-74.043845,29679,Customer,1997,1
366258,324,2019-08-31 23:50:27.9220,2019-08-31 23:55:52.8420,3276,Marin Light Rail,40.714584,-74.042817,3211,Newark Ave,40.721525,-74.046305,26198,Subscriber,1997,2
366259,126,2019-08-31 23:52:21.9250,2019-08-31 23:54:28.5820,3211,Newark Ave,40.721525,-74.046305,3209,Brunswick St,40.724176,-74.050656,29512,Subscriber,1998,1
366260,690,2019-08-31 23:56:55.1530,2019-09-01 00:08:25.2370,3185,City Hall,40.717732,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,26223,Subscriber,1992,1

In [32]:
# merging the files
joined_files = os.path.join("database", "JC-2020*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)
  
# Finally, the files are joined
df_two = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
df_two

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185564,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
185565,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
185566,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
185567,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
185568,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [33]:
result = pd.concat([df_one, df_two])
result

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185564,162,2020-08-31 23:43:15.8540,2020-08-31 23:45:58.4550,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,44787,Subscriber,1977,1
185565,400,2020-08-31 23:46:19.9130,2020-08-31 23:53:00.3610,3481,York St,40.716490,-74.041050,3187,Warren St,40.721124,-74.038051,19153,Subscriber,1986,1
185566,288,2020-08-31 23:47:16.8680,2020-08-31 23:52:05.5550,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,42434,Subscriber,1960,1
185567,199,2020-08-31 23:50:37.2650,2020-08-31 23:53:56.9490,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44226,Subscriber,1994,1
185568,333,2020-08-31 23:55:30.8050,2020-09-01 00:01:04.4110,3211,Newark Ave,40.721525,-74.046305,3270,Jersey & 6th St,40.725289,-74.045572,42437,Subscriber,1984,2

In [45]:
# merging the files
joined_files = os.path.join("database", "JC-2022*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)
  
# Finally, the files are joined
df_fr = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
df_fr

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7830EBE775F2EE25,classic_bike,2021-06-21 07:38:42,2021-06-21 10:49:25,Dixon Mills,JC076,NaN,NaN,40.721630,-74.049968,NaN,NaN,member
1,629A3BFD50BF8392,docked_bike,2021-06-12 10:25:01,2021-06-12 10:35:11,Dixon Mills,JC076,Journal Square,JC103,40.721630,-74.049967,40.733670,-74.062500,member
2,CF02EC434989A99D,docked_bike,2021-06-07 14:52:05,2021-06-07 14:58:25,11 St & Washington St,HB502,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.749984,-74.027150,40.735938,-74.030305,member
3,E1BB8FED29AA5BA1,docked_bike,2021-06-07 08:29:19,2021-06-07 08:34:17,8 St & Washington St,HB603,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.745983,-74.028199,40.735938,-74.030305,casual
4,787C59EE76D96BCA,docked_bike,2021-06-18 14:16:27,2021-06-18 14:26:26,11 St & Washington St,HB502,Columbus Park - Clinton St & 9 St,HB501,40.749984,-74.027150,40.748161,-74.032453,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
685212,D0F075EEE4354A37,electric_bike,2022-08-03 19:00:22,2022-08-03 19:07:13,City Hall - Washington St & 1 St,HB105,11 St & Washington St,HB502,40.737360,-74.030970,40.749985,-74.027150,member
685213,15DE9EFD3E032E69,classic_bike,2022-08-31 18:42:27,2022-08-31 18:47:01,City Hall - Washington St & 1 St,HB105,8 St & Washington St,HB603,40.737360,-74.030970,40.745984,-74.028199,member
685214,899BAFD096248F46,classic_bike,2022-08-24 14:26:28,2022-08-24 14:30:47,City Hall - Washington St & 1 St,HB105,8 St & Washington St,HB603,40.737360,-74.030970,40.745984,-74.028199,member
685215,AB474610295F3330,classic_bike,2022-08-24 18:50:31,2022-08-24 19:01:00,Riverview Park,JC057,11 St & Washington St,HB502,40.744757,-74.043725,40.749985,-74.027150,member
685216,1AC620345E6D2BF7,classic_bike,2022-08-31 08:52:20,2022-08-31 08:56:34,City Hall - Washington St & 1 St,HB105,8 St & Washington St,HB603,40.737360,-74.030970,40.745984,-74.028199,member

In [43]:
# merging the files
joined_files = os.path.join("database", "JC-2023*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)
  
# Finally, the files are joined
df_fv = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
df_fv

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
170355,BF0032DA4A305161,classic_bike,2023-03-19 16:25:24,2023-03-19 16:33:20,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,member
170356,32172F9BEF8D56A2,classic_bike,2023-03-22 16:14:15,2023-03-22 16:20:28,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual
170357,6FCF0C7C1E254341,electric_bike,2023-03-19 02:16:02,2023-03-19 02:21:15,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual
170358,34DFBEB02424B55E,electric_bike,2023-03-30 20:09:24,2023-03-30 20:15:08,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual
170359,A235AD010540ACA2,classic_bike,2023-03-17 17:53:28,2023-03-17 17:59:43,Madison St & 1 St,HB402,Columbus Park - Clinton St & 9 St,HB501,40.738790,-74.039300,40.748161,-74.032453,casual

In [48]:
result2 = pd.concat([df_tr, df_fr,df_fv])

result2

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,226.0,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186.0,Grove St PATH,40.719586,-74.043117,3211.0,Newark Ave,40.721525,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,377.0,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186.0,Grove St PATH,40.719586,-74.043117,3269.0,Brunswick & 6th,40.726012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,288.0,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186.0,Grove St PATH,40.719586,-74.043117,3269.0,Brunswick & 6th,40.726012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,435.0,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195.0,Sip Ave,40.730897,-74.063913,3280.0,Astor Place,40.719282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,231.0,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186.0,Grove St PATH,40.719586,-74.043117,3276.0,Marin Light Rail,40.714584,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-08-17 18:38:03,Grove St PATH,JC005,Jersey & 6th St,JC027,40.719586,-74.043117,40.725289,-74.045572,member
259461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-08-15 14:12:17,Grove St PATH,JC005,Morris Canal,JC072,40.719586,-74.043117,40.712419,-74.038526,member
259462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-08-29 19:53:45,Grove St PATH,JC005,Jersey & 6th St,JC027,40.719586,-74.043117,40.725289,-74.045572,member
259463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-08-26 21:15:22,Grove St PATH,JC005,Jersey & 6th St,JC027,40.719586,-74.043117,40.725289,-74.045572,member
259464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2021-08-13 00:01:13,Grove St PATH,JC005,Dixon Mills,JC076,40.719586,-74.043117,40.721630,-74.049968,member